# Generated by Django 6.0 on 2025-12-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiymlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Futbolka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('davlat', models.CharField(max_length=200)),
                ('brend', models.CharField(max_length=225)),
                ('info', models.CharField(max_length=200)),
                ('rang', models.CharField(max_length=200)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sotuvdagi_soni', models.IntegerField(default=0)),
            ],
        ),
    ]
